# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 400)
        MainWindow.setMinimumSize(QtCore.QSize(320, 400))
        MainWindow.setMaximumSize(QtCore.QSize(325, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.album_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.album_image.setGeometry(QtCore.QRect(100, 40, 131, 131))
        self.album_image.setText("")
        self.album_image.setPixmap(QtGui.QPixmap("Images/evermore.jpg"))
        self.album_image.setScaledContents(True)
        self.album_image.setObjectName("album_image")
        self.playButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(140, 190, 56, 21))
        self.playButton.setObjectName("playButton")
        self.skipButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.skipButton.setGeometry(QtCore.QRect(220, 190, 56, 21))
        self.skipButton.setObjectName("skipButton")
        self.reverseButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reverseButton.setGeometry(QtCore.QRect(60, 190, 56, 21))
        self.reverseButton.setObjectName("reverseButton")
        self.songTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.songTitle.setGeometry(QtCore.QRect(60, 220, 231, 20))
        self.songTitle.setObjectName("songTitle")
        self.Playlist_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Playlist_label.setGeometry(QtCore.QRect(30, 20, 51, 21))
        self.Playlist_label.setObjectName("Playlist_label")
        self.Volume_downButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Volume_downButton.setGeometry(QtCore.QRect(230, 250, 81, 21))
        self.Volume_downButton.setObjectName("Volume_downButton")
        self.Volume_upButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Volume_upButton.setGeometry(QtCore.QRect(130, 250, 71, 21))
        self.Volume_upButton.setObjectName("Volume_upButton")
        self.volume_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.volume_label.setGeometry(QtCore.QRect(50, 250, 71, 21))
        self.volume_label.setObjectName("volume_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 325, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.skipButton.setText(_translate("MainWindow", "Skip"))
        self.reverseButton.setText(_translate("MainWindow", "Reverse"))
        self.songTitle.setText(_translate("MainWindow", "long story short by Taylor Swift"))
        self.Playlist_label.setText(_translate("MainWindow", "Song 1/5"))
        self.Volume_downButton.setText(_translate("MainWindow", "Volume down"))
        self.Volume_upButton.setText(_translate("MainWindow", "Volume up"))
        self.volume_label.setText(_translate("MainWindow", "Volume: 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
