# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 400)
        MainWindow.setMinimumSize(QtCore.QSize(350, 400))
        MainWindow.setMaximumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.album_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.album_image.setGeometry(QtCore.QRect(90, 40, 161, 131))
        self.album_image.setText("")
        self.album_image.setObjectName("album_image")
        self.playButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(140, 190, 56, 21))
        self.playButton.setObjectName("playButton")
        self.skipButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.skipButton.setGeometry(QtCore.QRect(230, 190, 56, 21))
        self.skipButton.setObjectName("skipButton")
        self.reverseButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reverseButton.setGeometry(QtCore.QRect(50, 190, 56, 21))
        self.reverseButton.setObjectName("reverseButton")
        self.volumeSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.volumeSlider.setGeometry(QtCore.QRect(90, 240, 171, 16))
        self.volumeSlider.setMaximum(2)
        self.volumeSlider.setPageStep(1)
        self.volumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.volumeSlider.setObjectName("volumeSlider")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 260, 31, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 260, 181, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.songTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.songTitle.setGeometry(QtCore.QRect(90, 220, 171, 16))
        self.songTitle.setObjectName("songTitle")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 61, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.skipButton.setText(_translate("MainWindow", "Skip"))
        self.reverseButton.setText(_translate("MainWindow", "Reverse"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "      1"))
        self.label_4.setText(_translate("MainWindow", "           2"))
        self.songTitle.setText(_translate("MainWindow", "Song title"))
        self.label_5.setText(_translate("MainWindow", "Volume"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
